<?php

namespace Edumedics\DataModels\MapTraits;

trait FieldMapTrait
{

    protected $eligibility_field_map = [
        'external_id' => 'external_id',
        'claimant' => 'claimant',
        'member sequence number' => 'member_sequence',
        'member_sequence_number' => 'member_sequence',
        'member_sequence' => 'member_sequence',
        'relationship' => 'type',
        'type' => 'type',
        'gender' => 'gender',
        'memberid encrypted' => 'navmd_id',
        'memberid_encrypted' => 'navmd_id',
        'navmd_id' => 'navmd_id',
        'first name' => 'first_name',
        'first_name' => 'first_name',
        'last name' => 'last_name',
        'last_name' => 'last_name',
        'birth date' => 'date_of_birth',
        'birth_date' => 'date_of_birth',
        'date_of_birth' => 'date_of_birth',
        'address' => 'address',
        'city' => 'city',
        'state' => 'state',
        'zip code' => 'zip_code',
        'zip_code' => 'zip_code',
        'phone number' => 'home_phone',
        'phone_number' => 'home_phone',
        'home_number' => 'home_phone',
        'copd' => 'COPD',
        'dep' => 'Depression',
        'htn' => 'Hypertension',
        'hld' => 'Hyperlipidemia',
        'dm' => 'Diabetes',
        'wc' => 'Wellness Coaching',
        'biometrics' => 'Yearly Biometric Screens'
    ];

    protected $imported_programs = [
        'COPD',
        'Depression',
        'Hypertension',
        'Hyperlipidemia',
        'Diabetes',
        'Wellness Coaching',
        'Yearly Biometric Screens'
    ];

    protected $biometrics_field_map = [
        'external_id' => 'external_id',
        'claimant' => 'claimant',
        'first_name' => 'first_name',
        'last_name' => 'last_name',
        'birth_date' => 'date_of_birth',
        'date_of_birth' => 'date_of_birth',
        'date_of_service' => 'scheduled_time',
        'scheduled_time' => 'scheduled_time',
        'visit_reason' => 'reason',
        'icd10_codes' => 'icd10_codes',
        'height' => 'height',
        'weight' => 'weight',
        'diastolic_bp' => 'dbp',
        'dbp' => 'dbp',
        'systolic_bp' => 'sbp',
        'sbp' => 'sbp',
        'hgba1c' => 'a1c',
        'a1c' => 'a1c',
        'poc_glucose' => 'glucose',
        'glucose' => 'glucose',
        'ldlc' => 'ldl',
        'ldl' => 'ldl',
        'hdlcl' => 'hdl',
        'hdl' => 'hdl',
        'cholesterol' => 'cholesterol',
        'triglycerides' => 'tryglicerides',
        'waist' => 'waist_circumference',
        'fasting_status' => 'fasting',
        'gender' => 'gender'
    ];

    protected $employee_type_map = [
        'EMPLOYEE' => 1,
        'SELF' => 1, // EMPLOYEE
        'SPOUSE' => 2,
        'CHILD' => 3, // DEPENDENT
        'DEPENDENT' => 3,
        'RETIREE' => 4,
        'DOMESTIC PARTNER' => 5,
        'OTHER' => 6,
        'CH' => 3,
        'EE' => 1,
        'SP' => 2,
        'SUPPORT CHECKED/DEPENDENT CHILD' => 3,
        'STUDENT' => 6
    ];

    protected $demographics_field_map = [
        'external_id' => 'external_id',
        'memberid encrypted'=> 'navmd_id',
        'memberidencrypted' => 'navmd_id',
        'navmd_id' => 'navmd_id',
        'navmd id' => 'navmd_id',
        'employee_id' => 'employee_id',
        'employeeid' => 'employee_id',
        'employee id' => 'employee_id',
        'industry' => 'industry',
        'claimant' => 'claimant',
        'member sequence number' => 'member_sequence',
        'member_sequence_number' => 'member_sequence',
        'member_sequence' => 'member_sequence',
        'membersequencenumber' => 'member_sequence',
        'membersequence' => 'member_sequence',
        'relationship' => 'type',
        'type' => 'type',
        'education' => 'education',
        'voicemail' => 'voicemail',
        'voice mail' => 'voicemail',
        'voice_mail' => 'voicemail',
        'summary preference' => 'summary_preference',
        'summarypreference' => 'summary_preference',
        'summary_preference' => 'summary_preference',
        'date_of_birth' => 'date_of_birth',
        'dateofbirth' => 'date_of_birth',
        'dob' => 'date_of_birth',
        'date of birth' => 'date_of_birth',
        'gender' => 'gender',
        'address' => 'address',
        'city' => 'city',
        'ethnicity' => 'ethnicity',
        'race' => 'race',
        'first name' => 'first_name',
        'first_name' => 'first_name',
        'firstname' => 'first_name',
        'last name' => 'last_name',
        'last_name' => 'last_name',
        'lastname' => 'last_name',
        'middle_name' => 'middle_name',
        'middlename' => 'middle_name',
        'middle name' => 'middle_name',
        'maiden_name' => 'maiden_name',
        'maiden name' => 'maiden_name',
        'maidenname' => 'maiden_name',
        'nick_name' => 'nick_name',
        'nickname' => 'nick_name',
        'home_phone' => 'home_phone',
        'homephone' => 'home_phone',
        'home phone' => 'home_phone',
        'cell_phone' => 'cell_phone',
        'cellphone' => 'cell_phone',
        'cell phone' => 'cell_phone',
        'state' => 'state',
        'zip_code' => 'zip_code',
        'zipcode' => 'zip_code',
        'zip code' => 'zip_code',
        'email' => 'email',
        'e-mail' => 'email',
        'e_mail' => 'email',
        'e mail' => 'email',
        'doctor' => 'doctor',
        'provider' => 'doctor',
        'insurance_company' => 'insurance_company',
        'insurancecompany' => 'insurance_company',
        'insurance company' => 'insurance_company',
        'insurance_id_number' => 'insurance_id_number',
        'insuranceidnumber' => 'insurance_id_number',
        'insurance id number' => 'insurance_id_number',
        'insurance_group_number' => 'insurance_group_number',
        'insurancegroupnumber' => 'insurance_group_number',
        'insurance group number' => 'insurance_group_number',
        'preferred_language' => 'preferred_language',
        'preferred language' => 'preferred_language',
        'do_not_contact' => 'do_not_contact',
        'donotcontact' => 'do_not_contact',
        'do not contact' => 'do_not_contact',
        'dnc' => 'do_not_contact',
    ];

    protected $industries = ['21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54','55', '56', '61', '62', '71', '72', '81' ];

    protected $ethnicity_field_map = [
        'non-hispanic' => 'not_hispanic',
        'non hispanic' => 'not_hispanic',
        'non_hispanic' => 'not_hispanic',
        'not hispanic' => 'not_hispanic',
        'not-hispanic' => 'not_hispanic',
        'not_hispanic' => 'not_hispanic',
        'hispanic' => 'hispanic',
        'declined' => 'declined',
        'declined to answer' => 'declined',
        'declined_to_answer' => 'declined',
        'declinedtoanswer' => 'declined',
        'blank' => 'blank'
    ]; // "blank", "hispanic", "not_hispanic" or "declined"

    protected $race_field_map = [
        'blank' => 'blank',
        'other' => 'blank',
        'other race' => 'blank',
        'american indian or alaska native' => 'indian',
        'american indian' => 'indian',
        'alaska native' => 'indian',
        'native american' => 'indian',
        'indian' => 'indian',
        'asian' => 'asian',
        'black or african american' => 'black',
        'black' => 'black',
        'african american' => 'black',
        'native hawaiian or other pacific islander' => 'hawaiian',
        'hawaiian' => 'hawaiian',
        'native hawaiian' => 'hawaiian',
        'white or caucasian' => 'white',
        'white' => 'white',
        'caucasian' => 'white',
        'declined to answer' => 'declined',
        'declined' => 'declined'
    ]; // "blank", "indian", "asian", "black", "hawaiian", "white" or "declined"

    protected $gender_field_map = [
        'f' => 'Female',
        'female' => 'Female',
        'm' => 'Male',
        'male' => 'Male'
    ]; // Male or Female

    protected  $summary_preference_field_map = [
        'mail' => 'Standard Mail',
        'standard mail' => 'Standard Mail',
        'standard_mail' => 'Standard Mail',
        'email' => 'Email',
        'e-mail' => 'Email',
        'printed copy' => 'Printed Copy',
        'printed_copy' => 'Printed Copy',
        'printed' => 'Printed Copy',
        'copy' => 'Printed Copy'
    ]; // Standard Mail, Email or Printed Copy

    protected $preferred_language_field_map = [
        'blank' => 'blank',
        'eng' => 'eng',
        'english' => 'eng',
        'zho' => 'zho',
        'chinese' => 'zho',
        'fra' => 'fra',
        'french' => 'fra',
        'ita' => 'ita',
        'italian' => 'ita',
        'jpn' => 'jpn',
        'japanese' => 'jpn',
        'por' => 'por',
        'portuguese' => 'por',
        'rus' => 'rus',
        'russian' => 'rus',
        'spa' => 'spa',
        'spanish/castilian' => 'spa',
        'spanish / castilian' => 'spa',
        'spanish /castilian' => 'spa',
        'spanish/ castilian' => 'spa',
        'spanish' => 'spa',
        'castilian' => 'spa',
        'other' => 'other',
        'unknown' => 'unknown',
        'declined' => 'declined',
        'declined to specify' => 'declined'
    ]; // blank, eng, zho,fra, ita, jpn, por, rus, spa, other, unknown or declined

    protected $education_field_map = [
        'high school' => 'High School',
        'high_school' => 'High School',
        'some college' => 'Some College',
        'some_college' => 'Some College',
        'associate degree' => 'Associate Degree',
        'associate_degree' => 'Associate Degree',
        'bachelor degree' => 'Bachelor Degree',
        'bachelor_degree' => 'Bachelor Degree',
        'graduate degree' => 'Graduate Degree',
        'graduate_degree' => 'Graduate Degree',
        'doctorate degree' => 'Doctorate Degree',
        'doctorate_degree' => 'Doctorate Degree'
    ]; // "High School", "Some College", "Associate Degree", "Bachelor Degree","Graduate Degree" or "Doctorate Degree"
}